stages:
  prepare:
    cmd: python prepare.py reddit_scrapper/data/scrapped_data.json reddit_scrapper/data/list_of_unique_subreddits.json
    deps:
    - prepare.py
    - reddit_scrapper/data/list_of_unique_subreddits.json
    - reddit_scrapper/data/scrapped_data.json
    params:
    - prepare.lower_limit
    - prepare.upper_limit
    outs:
    - prepared/matrix.csv
    - prepared/matrix_bool.csv
  generate_association_rules_final:
    cmd: python generate_association_rules_final.py prepared/matrix_bool.csv
    deps:
      - generate_association_rules_final.py
      - prepared/matrix_bool.csv
    params:
      - generate_association_rules_final.min_support
    outs:
      - target/arules-10000-00035.json
  cluster_PCA:
    cmd: python cluster_PCA.py prepared/matrix.csv
    deps:
      - cluster_PCA.py
      - prepared/matrix.csv
    params:
      - cluster_PCA.n_components
      - cluster_PCA.n_clusters
    outs:
      - target/pca.csv
  cluster_TSNA:
    cmd: python cluster_TSNA.py prepared/matrix.csv
    deps:
      - cluster_TSNA.py
      - prepared/matrix.csv
    params:
      - cluster_TSNA.n_components
      - cluster_TSNA.n_jobs
      - cluster_TSNA.random_state
    outs:
      - target/tsna.csv
      - target/tsna.pkl
  scrape_user:
    cmd: python scrape_user.py
    params:
      - scrape_user.username
    outs:
      - target/user.json
  recommend:
    cmd: python recommend.py target/arules-10000-00035.json target/user.json target/tsna.csv target/tsna.pkl target/pca.csv
    deps:
      - recommend.py
      - target/arules-10000-00035.json
      - target/user.json
      - target/tsna.csv
      - target/tsna.pkl
      - target/pca.csv