prepare:
  upper_limit: 2000
  lower_limit: 3
generate_association_rules_final:
  upper_limit: 5000
  min_support: 0.00035
cluster_TSNA:
  n_components: 3
  n_jobs: -1
  random_state: 42
cluster_PCA:
  n_components: 200
  n_clusters: 700
scrape_user:
  username: FirstGalacticEmpire