prepare:
  upper_limit: 2000
  lower_limit: 3
  upper_limit_arules: 10000
  lower_limit_arules: 20
generate_association_rules_final:
  min_support: 0.00035
cluster_TSNA:
  n_components: 3
  n_jobs: -1
  random_state: 42
cluster_PCA:
  n_components: 200
  n_clusters: 700
scrape_user:
  username: FirstGalacticEmpire